### ISSUE TITLE
License or use as a mini-game?

### ISSUE THREAD

**Issue by markmehere** [Mikhail-MM/React-Poker#19]
Really enjoyed this! I've been getting into [Game Jams](https://itch.io/jams) recently and found it worked well as mini-game (game inside another often RPG game). But I'm not sure how/if you want people using it in this way. Let folks know your wishes! There aren't a whole lot of open source Javascript games at the moment.

**Comment by Mikhail-MM** [comment]
Use it, steal it, whatever
